select STARNAME
from STARSIN
WHERE STARNAME LIKE '%n' AND MOVIETITLE NOT LIKE '%Wars%'

select *
from STARSIN
WHERE STARNAME LIKE '% %n' AND MOVIETITLE NOT LIKE '%Wars%'

SELECT STARNAME
FROM STARSIN
WHERE STARNAME LIKE '%n' AND MOVIETITLE NOT LIKE '%Wars%'


SELECT ADDRESS
FROM  STUDIO 
WHERE NAME =( SELECT STUDIONAME
	       FROM MOVIE
              WHERE TITLE = 'Gone with the Wind')
