/*select *
from MOVIE
WHERE STUDIONAME='MGM'
ORDER BY length desc , year desc/asc,  */


---outer join
/*select
from
full outer join
on */

-- full / left/right

/*select * 
from MOVIESTAR

SELECT *
FROM MOVIEEXEC*/

/*select *
from MOVIESTAR,MOVIEEXEC
WHERE MOVIESTAR.NAME= MOVIEEXEC.NAME AND MOVIESTAR.ADDRESS=MOVIEEXEC.ADDRESS*/

SELECT *
FROM MOVIESTAR
FULL OUTER JOIN MOVIEEXEC
ON MOVIESTAR.NAME= MOVIEEXEC.NAME AND MOVIESTAR.ADDRESS=MOVIEEXEC.ADDRESS

-- DANGLING YAPAMIYORSAK OLUYORDUR BÝRLEÞTÝREMÝYORSAK DANGLING



